name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: hdvalen/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: "hdvalen"
      - name: Commit & Push
        run: |
          git config user.name hdvalen
          git config user.email 145690430+hdvalen@users.noreply.github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
